environment:
    CCACHE_BASEDIR: $CIRRUS_WORKING_DIR

    # Enforce sequential JIT'ing of files for controlled memory usage.
    HILTI_JIT_SEQUENTIAL: 1

    # Images for macOS
    IMAGE_MACOS_BIG_SUR:  big-sur-base
    IMAGE_MACOS_CATALINA: catalina-base

zkg_ubuntu_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    matrix:
      - docker_arguments:
        - ZEEK_LTS: 1
        - ZEEK_VERSION: 4.0.3-0
    cpu: 2
    memory: 8G

  install_spicy_script:
    - curl -o spicy-dev.deb https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/spicy-dev.deb
    - dpkg --install spicy-dev.deb
    - rm spicy-dev.deb

  test_script:
    - zkg test .

  install_script:
    # --force avoids prompts, --skiptests because tests ran already
    - zkg install --force --skiptests .

  check_script:
    - zeek -N Zeek::Spicy
    - zeek local

  always:
      stderr_script: ./ci/show-zkg-stderr

standalone_ubuntu_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    matrix:
      - docker_arguments:
        - ZEEK_LTS:
        - ZEEK_VERSION: 4.0.3-0
    cpu: 2
    memory: 8G

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  install_spicy_script:
    - curl -o spicy-dev.deb https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/spicy-dev.deb
    - dpkg --install spicy-dev.deb
    - rm spicy-dev.deb

  build_script:
    - (mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/opt/spicy-plugin -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja .. && ninja -j4)

  clang_tidy_script:
    - (cd build && run-clang-tidy -j $(nproc) $(jq -r '.[].file | select(contains(".bif") | not)' <compile_commands.json ))

  test_build_script:
    - ZEEK_PLUGIN_PATH=$(pwd)/build zeek -N Zeek::Spicy
    - make -C tests test

  install_script:
    - (cd build && ninja install)
    - rm -rf build

  test_install_script:
    - zeek -N Zeek::Spicy
    - PATH=/opt/spicy-plugin/bin:$PATH make -C tests test-install

static_zeek_master_ubuntu_task:
  timeout_in: 120m
  container:
    dockerfile: ci/Dockerfile
    cpu: 2
    memory: 8G

  env:
    CCACHE_DIR: /tmp/ccache
    CCACHE_COMPRESS: 1

  always:
    ccache_cache:
      folder: /tmp/ccache
      fingerprint_script: echo $CIRRUS_TASK_NAME-$CIRRUS_OS

  install_spicy_script:
    - curl -o spicy-dev.deb https://api.cirrus-ci.com/v1/artifact/github/zeek/spicy/docker_ubuntu20/packages/spicy-dev.deb
    - dpkg --install spicy-dev.deb
    - rm spicy-dev.deb

  clone_zeek_script:
    - git clone --recursive https://github.com/zeek/zeek

  build_script:
    - (cd zeek && ./configure --include-plugins=$CIRRUS_WORKING_DIR --generator=Ninja --ccache --prefix=/opt/zeek-master --disable-zeekctl --disable-python && cd build && ninja -j4)

  install_script:
    - (cd zeek/build && ninja install)

  # Note that the build tests need the Zeek headers installed.
  test_build_script:
    - (. zeek/build/zeek-path-dev.sh && ./zeek/build/src/zeek -N Zeek::Spicy)
    - PATH=$(pwd)/zeek/build/src:$(pwd)/zeek/build/src/builtin-plugins/$(basename $(pwd))/bin:$PATH make -C tests test

  test_install_script:
    - rm -rf zeek/build
    - PATH=/opt/zeek-master/bin:$PATH zeek -N Zeek::Spicy
    - PATH=/opt/zeek-master/bin:$PATH make -C tests test-install
